/**
 * POST /api/b2b-register
 *
 * Public endpoint — no auth required.
 * Customer self-registers using an admin-generated invite token.
 *
 * Body: { invite: string, full_name, email, phone, password, ...b2b_details }
 */
import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { consumeInviteToken } from "@/lib/invite-token";
import { syncContactToZoho, buildCustomerLink, generateNextCustomerNumber } from "@/lib/b2b-customer"
export async function POST(request: Request) {
  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  // Verify and consume the invite token (single-use enforcement).
  // The admin client is created here so it can be reused for subsequent DB operations.
  const admin = createAdminClient();
  const invite = String(body.invite ?? "");
  const { valid, error: tokenError, meta } = await consumeInviteToken(invite, admin);
  if (!valid) {
    return NextResponse.json({ error: tokenError ?? "Invalid invite link" }, { status: 400 });
  }

  // warehouse_id is embedded in the token when generated by a warehouse admin;
  // null means this was a regular admin invite (no warehouse scoping).
  const warehouseId = meta?.warehouse_id ?? null;

  const str = (v: unknown, fallback = "") =>
    typeof v === "string" ? v.trim() || fallback : fallback;
  const strOrNull = (v: unknown) => (typeof v === "string" && v.trim() ? v.trim() : null);

  const full_name = str(body.full_name);
  const email = str(body.email).toLowerCase();
  const phone = strOrNull(body.phone);
  const password = str(body.password);

  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return NextResponse.json({ error: "Valid email is required" }, { status: 400 });
  }
  if (!password || password.length < 6) {
    return NextResponse.json({ error: "Password must be at least 6 characters" }, { status: 400 });
  }
  if (!full_name) {
    return NextResponse.json({ error: "Full name is required" }, { status: 400 });
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = admin as any;

  // Create Supabase auth user
  const { data: authData, error: authError } = await admin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: { full_name, phone },
  });

  if (authError) {
    const msg = authError.message.includes("already registered")
      ? "An account with this email already exists"
      : authError.message;
    return NextResponse.json({ error: msg }, { status: 400 });
  }

  const userId = authData.user.id;

  // Update profile — set warehouse_id only if the invite was generated by a warehouse admin.
  // Retry once to handle the rare timing gap between GoTrue committing the auth
  // user and the on_auth_user_created trigger inserting the profile row.
  const profileUpdate: Record<string, unknown> = { full_name, phone, user_type: "b2b" };
  if (warehouseId) profileUpdate.warehouse_id = warehouseId;

  let { error: profileError, count: profileCount } = await db
    .from("profiles")
    .update(profileUpdate, { count: "exact" })
    .eq("id", userId);

  if (!profileError && (profileCount ?? 0) === 0) {
    // Profile row not yet created by trigger — wait briefly and retry.
    await new Promise((r) => setTimeout(r, 400));
    ({ error: profileError, count: profileCount } = await db
      .from("profiles")
      .update(profileUpdate, { count: "exact" })
      .eq("id", userId));
  }

  if (profileError) {
    console.error("[POST /api/b2b-register] Profile update failed:", profileError);
    await admin.auth.admin.deleteUser(userId).catch(() => {});
    return NextResponse.json(
      { error: "Failed to configure user profile: " + profileError.message },
      { status: 500 }
    );
  }

  if ((profileCount ?? 0) === 0) {
    console.error("[POST /api/b2b-register] Profile row missing after retry for user:", userId);
    await admin.auth.admin.deleteUser(userId).catch(() => {});
    return NextResponse.json(
      { error: "User profile was not initialised. Please try again." },
      { status: 500 }
    );
  }

  await admin.auth.admin.updateUserById(userId, { app_metadata: { user_type: "b2b" } });

  // Save B2B details
  const customerNumber = await generateNextCustomerNumber();
  const details = {
    user_id: userId,
    display_name:       strOrNull(body.display_name) ?? full_name,
    customer_number:    customerNumber,
    company_name:       strOrNull(body.company_name),
    contact_name:       strOrNull(body.contact_name),
    payment_terms:      strOrNull(body.payment_terms) ?? "Advance Payment",
    gst_treatment:      strOrNull(body.gst_treatment) ?? "Business - Registered",
    gstin:              strOrNull(body.gstin),
    billing_attention:  strOrNull(body.billing_attention),
    billing_address:    strOrNull(body.billing_address),
    billing_street2:    strOrNull(body.billing_street2),
    billing_city:       strOrNull(body.billing_city),
    billing_state:      strOrNull(body.billing_state),
    billing_country:    strOrNull(body.billing_country) ?? "India",
    billing_county:     strOrNull(body.billing_county),
    billing_phone:      strOrNull(body.billing_phone),
    shipping_attention: strOrNull(body.shipping_attention),
    shipping_address:   strOrNull(body.shipping_address),
    shipping_street2:   strOrNull(body.shipping_street2),
    shipping_city:      strOrNull(body.shipping_city),
    shipping_state:     strOrNull(body.shipping_state),
    shipping_country:   strOrNull(body.shipping_country) ?? "India",
    shipping_code:      strOrNull(body.shipping_code),
    shipping_phone:     strOrNull(body.shipping_phone),
  };

  await db.from("b2b_customer_details").insert(details);

  // Fire-and-forget: sync to Zoho Books so GSTIN and all details appear there
  void syncContactToZoho(email, full_name, phone, details);

  const customerLink = buildCustomerLink(userId);
  return NextResponse.json({ success: true, customerLink }, { status: 201 });
}
